- name: Set sysctl hardening config file
  ansible.builtin.template:
    src: 10-hardening.conf
    dest: /etc/sysctl.d/10-hardening.conf
    owner: root
    group: root
    mode: 0640

- name: Apply sysctl config
  ansible.builtin.command: sysctl --system
